import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Eventura Design Tokens ─────────────────────────────── */
        "outline-variant": "#c7c5d4",
        "on-tertiary-fixed-variant": "#574500",
        "primary-fixed-dim": "#c0c1ff",
        "surface-tint": "#4f54b4",
        "on-primary-container": "#9da1ff",
        "on-secondary-container": "#57657a",
        "inverse-primary": "#c0c1ff",
        "surface-container-high": "#eae7f0",
        "on-primary-fixed-variant": "#373a9b",
        "primary-container": "#2e3192",
        "surface": "#fcf8ff",
        "on-secondary-fixed": "#0d1c2e",
        "on-primary-fixed": "#04006d",
        "surface-bright": "#fcf8ff",
        "secondary": "#515f74",
        "primary": "#15157d",
        "surface-variant": "#e4e1ea",
        "tertiary": "#735c00",
        "secondary-container": "#d5e3fc",
        "on-background": "#1b1b21",
        "background": "#fcf8ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary-fixed": "#ffe088",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d5e3fc",
        "inverse-on-surface": "#f2eff8",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b21",
        "surface-dim": "#dbd9e1",
        "on-tertiary-fixed": "#241a00",
        "surface-container-highest": "#e4e1ea",
        "on-surface-variant": "#464652",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b9c7df",
        "on-error": "#ffffff",
        "surface-container": "#f0ecf5",
        "inverse-surface": "#303036",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        "outline": "#777683",
        "tertiary-container": "#cca730",
        "surface-container-low": "#f5f2fb",
        "on-tertiary-container": "#4f3d00",
        "on-secondary-fixed-variant": "#3a485b",
        /* ── Shadcn CSS Variable Colors ─────────────────────────── */
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "var(--radius)",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        md: "16px",
        gutter: "24px",
        lg: "24px",
        xs: "4px",
        "margin-mobile": "16px",
        xl: "40px",
        "margin-desktop": "48px",
        unit: "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
